laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    // Páginas Institucionais
    Route::get('/', 'HomeController@index')->name('home');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::get('pagina/{paginas}', 'PaginasController@index')->name('paginas');
    Route::get('lojas', 'LojaController@index')->name('loja');
    Route::get('trabalhe-conosco', 'TrabalheConoscoController@index')->name('trabalhe-conosco');
    Route::post('trabalhe-conosco', 'TrabalheConoscoController@post')->name('trabalhe-conosco.post');
    Route::get('fale-conosco', 'ContatoController@index')->name('fale-conosco');
    Route::post('fale-conosco', 'ContatoController@post')->name('fale-conosco.post');

    // Produtos
    Route::get('produtos/busca', 'ProdutosController@busca')->name('produtos.busca');
    Route::get('produtos/promocoes', 'ProdutosController@promocoes')->name('produtos.promocoes');
    Route::get('produtos/marcas/{marcas?}', 'ProdutosController@marcas')->name('produtos.marcas');
    Route::get('produtos/detalhe/{produtos}', 'ProdutosController@detalhe')->name('produtos.detalhe');
    Route::get('produtos/{secoes}', 'ProdutosController@secao')->name('produtos.secao');
    Route::get('produtos/{secoes}/{categorias}', 'ProdutosController@categoria')->name('produtos.categoria');
    Route::get('produtos/{secoes}/{categorias}/{subcategorias}', 'ProdutosController@subcategoria')->name('produtos.subcategoria');

    Route::group(['prefix' => 'orcamento'], function() {
        Route::get('/', 'OrcamentoController@index')->name('orcamento');
        Route::post('store', 'OrcamentoController@store')->name('orcamento.store');
        Route::post('update', 'OrcamentoController@update')->name('orcamento.update');
        Route::delete('destroy', 'OrcamentoController@destroy')->name('orcamento.destroy');
        Route::post('frete', 'OrcamentoController@frete')->name('orcamento.frete');
        Route::post('post', 'OrcamentoController@post')->name('orcamento.post');
    });


    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::resource('produtos.relacionados', 'ProdutosRelacionadosController', ['except' => ['edit', 'update']]);
        Route::resource('produtos.medidas', 'ProdutosMedidasController');
		Route::get('produtos/{produtos}/imagens/clear', [
			'as'   => 'painel.produtos.imagens.clear',
			'uses' => 'ProdutosImagensController@clear'
        ]);
        Route::resource('produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'imagens_produtos']]);
        Route::resource('produtos/marcas', 'ProdutosMarcasController');
        Route::resource('produtos/propriedades', 'ProdutosPropriedadesController');
        Route::resource('produtos/destaques', 'ProdutosDestaquesController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('produtos/promocoes', 'ProdutosPromocoesController', [
            'only' => ['index', 'destroy']
        ]);
        Route::get('produtos/{secoes}/destaque', 'ProdutosSecoesController@edit')->name('painel.produtos.{secoes}.destaque.edit');
        Route::match(['PUT', 'PATCH'], 'produtos/{secoes}/destaque', 'ProdutosSecoesController@update')->name('painel.produtos.{secoes}.destaque.update');
        Route::resource('produtos/{secoes}/categorias', 'ProdutosCategoriasController');
        Route::resource('produtos/{secoes}/categorias.subcategorias', 'ProdutosSubcategoriasController');
        Route::resource('produtos/{secoes}', 'ProdutosController', [
            'only' => ['index', 'create', 'store']
        ]);
        Route::get('produtos/{secoes}/{produtos}/edit', 'ProdutosController@edit')->name('painel.produtos.{secoes}.edit');
        Route::match(['PUT', 'PATCH'], 'produtos/{secoes}/{produtos}', 'ProdutosController@update')->name('painel.produtos.{secoes}.update');
        Route::delete('produtos/{secoes}/{produtos}', 'ProdutosController@destroy')->name('painel.produtos.{secoes}.destroy');

		Route::resource('banners', 'BannersController');
        Route::resource('paginas', 'PaginasController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('paginas.imagens', 'PaginasImagensController', [
            'except' => ['edit', 'update'],
            'parameters' => ['imagens' => 'paginas_imagens']
        ]);
        Route::resource('frete', 'FreteController');
        Route::resource('curriculos', 'CurriculosController', [
            'only' => ['index', 'show', 'destroy']
        ]);
        Route::resource('newsletter', 'NewsletterController', [
            'only' => ['index', 'destroy']
        ]);
        Route::get('newsletter/exportar', 'NewsletterController@exportar')
            ->name('painel.newsletter.exportar');

        Route::get('orcamentos/{orcamentos}/toggle', [
            'as' => 'painel.orcamentos.toggle',
            'uses' => 'OrcamentosController@toggle'
            ]);
        Route::resource('orcamentos', 'OrcamentosController');

        Route::get('contato/recebidos/{recebidos}/toggle', [
            'as' => 'painel.contato.recebidos.toggle',
            'uses' => 'ContatosRecebidosController@toggle'
            ]);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('configuracoes', 'ConfiguracoesController', [
            'only' => ['index', 'update']
        ]);
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('fetch-subcategorias/{id}', function($id) {
            $categoria = \App\Models\ProdutoCategoria::findOrFail($id);
            return $categoria->subcategorias->lists('titulo', 'id');
        });
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ConfiguracoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Configuracoes;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracoes::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracoes $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracoes::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            if (request()->file('imagem')) {
                $input['imagem'] = Contato::upload_imagem();
            }

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }

    public function toggle(ContatoRecebido $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/CurriculosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\Curriculo;

class CurriculosController extends Controller
{
    public function index()
    {
        $curriculos = Curriculo::latest()->paginate(15);

        return view('painel.curriculos.index', compact('curriculos'));
    }

    public function show(Curriculo $curriculo)
    {
        $curriculo->marcaComoLido();

        $arquivo = public_path('curriculos/'.$curriculo->arquivo);

        return response()->download($arquivo);
    }

    public function destroy(Curriculo $curriculo)
    {
        try {

            $curriculo->delete();
            return redirect()->route('painel.curriculos.index')->with('success', 'Currículo excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir currículo: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/FreteController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests;

use App\Models\Frete;

class FreteController extends Controller
{
    public function index()
    {
        $registros = Frete::all();

        return view('painel.frete.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.frete.create');
    }

    protected function validateAllFieldsRequired()
    {
        return $this->validate(request(), array_map(function() {
            return 'required';
        }, request()->except('_token')));
    }

    public function store()
    {
        $this->validateAllFieldsRequired();

        try {

            $input = request()->all();

            Frete::create($input);

            return redirect()->route('painel.frete.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Frete $registro)
    {
        return view('painel.frete.edit', compact('registro'));
    }

    public function update(Frete $registro)
    {
        $this->validateAllFieldsRequired();

        try {

            $input = request()->all();

            $registro->update($input);

            return redirect()->route('painel.frete.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Frete $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.frete.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/NewsletterController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;

use App\Models\Newsletter;
use Maatwebsite\Excel\Facades\Excel;
use Carbon\Carbon;

class NewsletterController extends Controller
{
    public function index()
    {
        $registros = Newsletter::ordenados()->paginate(30);

        return view('painel.newsletter.index', compact('registros'));
    }

    public function destroy(Newsletter $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.newsletter.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

    public function exportar()
    {
        $registros = Newsletter::ordenados()->get([
            'created_at as data', 'nome', 'email as e-mail'
        ])->each(function ($model) {
            $model->data = Carbon::parse($model->data)->format('d/m/Y H:i');
        });

        $fileName = 'jabaquaracolchoes-newsletter_'.date('d-m-Y_H-i');

        Excel::create($fileName, function ($excel) use ($registros) {
            $excel->sheet('newsletter', function ($sheet) use ($registros) {
                $sheet->fromModel($registros);
            });
        })->download('xls');
    }
}

laravel/app/Http/Controllers/Painel/ProdutosDestaquesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\ProdutoDestaque;

class ProdutosDestaquesController extends Controller
{
    public function index()
    {
        $registros = ProdutoDestaque::with('produto')->ordenados()->get();

        return view('painel.produtos.destaques.index', compact('registros'));
    }

    public function destroy(ProdutoDestaque $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.produtos.destaques.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*'])) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
	<li @if(Tools::routeIs('painel.banners*')) class="active" @endif>
		<a href="{{ route('painel.banners.index') }}">Banners</a>
	</li>
    <li class="dropdown @if(Tools::routeIs('painel.produtos*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Produtos
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            @foreach($secoes as $secao)
            <li @if(Route::current()->hasParameter('secoes') && Route::current()->parameter('secoes')->id == $secao->id) class="active" @endif>
                <a href="{{ route('painel.produtos.{secoes}.index', $secao) }}">{{ $secao->titulo }}</a>
            </li>
            @endforeach
            <li class="divider"></li>
            <li @if(Tools::routeIs('painel.produtos.marcas*')) class="active" @endif>
                <a href="{{ route('painel.produtos.marcas.index') }}">Marcas</a>
            </li>
            <li @if(Tools::routeIs('painel.produtos.propriedades*')) class="active" @endif>
                <a href="{{ route('painel.produtos.propriedades.index') }}">Propriedades</a>
            </li>
            <li class="divider"></li>
            <li @if(Tools::routeIs('painel.produtos.destaques*')) class="active" @endif>
                <a href="{{ route('painel.produtos.destaques.index') }}">Destaques</a>
            </li>
            <li @if(Tools::routeIs('painel.produtos.promocoes*')) class="active" @endif>
                <a href="{{ route('painel.produtos.promocoes.index') }}">Promoções</a>
            </li>
        </ul>
    </li>
	<li @if(Tools::routeIs('painel.paginas*')) class="active" @endif>
		<a href="{{ route('painel.paginas.index') }}">Páginas</a>
    </li>
    <li @if(Tools::routeIs('painel.frete*')) class="active" @endif>
		<a href="{{ route('painel.frete.index') }}">Frete</a>
    </li>
    <li class="dropdown @if(Tools::routeIs('painel.contato*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.contato.index')) class="active" @endif>
                <a href="{{ route('painel.contato.index') }}">Informações de Contato</a>
            </li>
            <li @if(Tools::routeIs('painel.contato.recebidos*')) class="active" @endif>
                <a href="{{ route('painel.contato.recebidos.index') }}">
                    Contatos Recebidos
                    @if($contatosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                    @endif
                </a>
            </li>
        </ul>
    </li>
    <li @if(Tools::routeIs('painel.curriculos*')) class="active" @endif>
        <a href="{{ route('painel.curriculos.index') }}">
            Currículos
            @if($curriculosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $curriculosNaoLidos }}</span>
            @endif
        </a>
    </li>
    <li @if(Tools::routeIs('painel.newsletter*')) class="active" @endif>
        <a href="{{ route('painel.newsletter.index') }}">
            Newsletter
            @if($countNewsletter)
            <span class="label label-primary" style="background:rgba(255,255,255,.2);margin-left:3px">{{ $countNewsletter }}</span>
            @endif
        </a>
    </li>
    <li @if(Tools::routeIs('painel.orcamentos*')) class="active" @endif>
        <a href="{{ route('painel.orcamentos.index') }}">
            Orçamentos
            @if($orcamentosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $orcamentosNaoLidos }}</span>
            @endif
        </a>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/selectize/dist/css/selectize.bootstrap3.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/vendor/selectize/dist/js/standalone/selectize.min.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>
    <script src="{{ asset('assets/jquery.maskmoney.js') }}"></script>
    <script>$('.num-frete').maskMoney({ allowZero: true });</script>
    <script>$('.select-filter').selectize();</script>
</body>
</html>