laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    // Páginas Institucionais
    Route::get('/', 'HomeController@index')->name('home');
    Route::post('newsletter', 'HomeController@newsletter')->name('newsletter');
    Route::get('pagina/{paginas}', 'PaginasController@index')->name('paginas');
    Route::get('lojas', 'LojaController@index')->name('loja');
    Route::get('trabalhe-conosco', 'TrabalheConoscoController@index')->name('trabalhe-conosco');
    Route::post('trabalhe-conosco', 'TrabalheConoscoController@post')->name('trabalhe-conosco.post');
    Route::get('fale-conosco', 'ContatoController@index')->name('fale-conosco');
    Route::post('fale-conosco', 'ContatoController@post')->name('fale-conosco.post');

    // Produtos
    Route::get('produtos/busca', 'ProdutosController@busca')->name('produtos.busca');
    Route::get('produtos/promocoes', 'ProdutosController@promocoes')->name('produtos.promocoes');
    Route::get('produtos/marcas/{marcas?}', 'ProdutosController@marcas')->name('produtos.marcas');
    Route::get('produtos/detalhe/{produtos}', 'ProdutosController@detalhe')->name('produtos.detalhe');
    Route::get('produtos/{secoes}', 'ProdutosController@secao')->name('produtos.secao');
    Route::get('produtos/{secoes}/{categorias}', 'ProdutosController@categoria')->name('produtos.categoria');
    Route::get('produtos/{secoes}/{categorias}/{subcategorias}', 'ProdutosController@subcategoria')->name('produtos.subcategoria');

    Route::group(['prefix' => 'orcamento'], function() {
        Route::get('/', 'OrcamentoController@index')->name('orcamento');
        Route::post('store', 'OrcamentoController@store')->name('orcamento.store');
        Route::post('update', 'OrcamentoController@update')->name('orcamento.update');
        Route::delete('destroy', 'OrcamentoController@destroy')->name('orcamento.destroy');
        Route::post('frete', 'OrcamentoController@frete')->name('orcamento.frete');
        Route::post('post', 'OrcamentoController@post')->name('orcamento.post');
    });


    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::resource('produtos.relacionados', 'ProdutosRelacionadosController', ['except' => ['edit', 'update']]);
        Route::resource('produtos.medidas', 'ProdutosMedidasController');
		Route::get('produtos/{produtos}/imagens/clear', [
			'as'   => 'painel.produtos.imagens.clear',
			'uses' => 'ProdutosImagensController@clear'
        ]);
        Route::resource('produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'imagens_produtos']]);
        Route::resource('produtos/marcas', 'ProdutosMarcasController');
        Route::resource('produtos/propriedades', 'ProdutosPropriedadesController');
        Route::resource('produtos/destaques', 'ProdutosDestaquesController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('produtos/promocoes', 'ProdutosPromocoesController', [
            'only' => ['index', 'destroy']
        ]);
        Route::get('produtos/{secoes}/destaque', 'ProdutosSecoesController@edit')->name('painel.produtos.{secoes}.destaque.edit');
        Route::match(['PUT', 'PATCH'], 'produtos/{secoes}/destaque', 'ProdutosSecoesController@update')->name('painel.produtos.{secoes}.destaque.update');
        Route::resource('produtos/{secoes}/categorias', 'ProdutosCategoriasController');
        Route::resource('produtos/{secoes}/categorias.subcategorias', 'ProdutosSubcategoriasController');
        Route::resource('produtos/{secoes}', 'ProdutosController', [
            'only' => ['index', 'create', 'store']
        ]);
        Route::get('produtos/{secoes}/{produtos}/edit', 'ProdutosController@edit')->name('painel.produtos.{secoes}.edit');
        Route::match(['PUT', 'PATCH'], 'produtos/{secoes}/{produtos}', 'ProdutosController@update')->name('painel.produtos.{secoes}.update');
        Route::delete('produtos/{secoes}/{produtos}', 'ProdutosController@destroy')->name('painel.produtos.{secoes}.destroy');

		Route::resource('banners', 'BannersController');
        Route::resource('paginas', 'PaginasController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('paginas.imagens', 'PaginasImagensController', [
            'except' => ['edit', 'update'],
            'parameters' => ['imagens' => 'paginas_imagens']
        ]);
        Route::resource('frete', 'FreteController');
        Route::resource('curriculos', 'CurriculosController', [
            'only' => ['index', 'show', 'destroy']
        ]);
        Route::resource('newsletter', 'NewsletterController', [
            'only' => ['index', 'destroy']
        ]);
        Route::get('newsletter/exportar', 'NewsletterController@exportar')
            ->name('painel.newsletter.exportar');

        Route::get('orcamentos/{orcamentos}/toggle', [
            'as' => 'painel.orcamentos.toggle',
            'uses' => 'OrcamentosController@toggle'
            ]);
        Route::resource('orcamentos', 'OrcamentosController');

        Route::get('contato/recebidos/{recebidos}/toggle', [
            'as' => 'painel.contato.recebidos.toggle',
            'uses' => 'ContatosRecebidosController@toggle'
            ]);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('configuracoes', 'ConfiguracoesController', [
            'only' => ['index', 'update']
        ]);
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('fetch-subcategorias/{id}', function($id) {
            $categoria = \App\Models\ProdutoCategoria::findOrFail($id);
            return $categoria->subcategorias->lists('titulo', 'id');
        });
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Orcamento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Orcamento extends Model
{
    protected $table = 'orcamentos';

    protected $guarded = ['id'];

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

    public function getCreatedAtOrderAttribute()
    {
        return \Carbon\Carbon::createFromFormat('d/m/Y', $this->created_at)->format('Y-m-d');
    }

    public function scopeNaoLidos($query)
    {
        return $query->where('lido', '!=', 1);
    }

    public function countNaoLidos()
    {
        return $this->naoLidos()->count();
    }
}

laravel/app/Http/Controllers/OrcamentoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\OrcamentosRequest;

use App\Models\ProdutoMedida;
use App\Models\Frete;
use App\Models\Orcamento;
use App\Models\Contato;

use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Mail;

use App\Helpers\Tools;

class OrcamentoController extends Controller
{
    public function index()
    {
        $medidas    = $this->medidasOrcamento();
        $valorTotal = $this->valorTotal($medidas);

        return view('frontend.orcamento', compact('medidas', 'valorTotal'));
    }

    public function store()
    {
        $medida = ProdutoMedida::find(request('medida'));

        if (! $medida || ! $medida->produto->ativo) return back();

        $orcamento = session('orcamento', []);

        if (array_key_exists($medida->id, $orcamento)) {
            $orcamento[$medida->id] += 1;
        } else {
            $orcamento[$medida->id] = 1;
        }

        session()->put('orcamento', $orcamento);

        return redirect()->route('orcamento');
    }

    public function update()
    {
        $this->validate(request(), ['quantidade' => 'regex:/[0-9]+/']);

        $medida = ProdutoMedida::find(request('medida'));

        if (! $medida || ! $medida->produto->ativo) return back();

        $orcamento = session('orcamento', []);

        if (array_key_exists($medida->id, $orcamento) && $quantidade = request('quantidade')) {
            $orcamento[$medida->id] = (int)$quantidade;
        }

        if ($quantidade == 0) {
            unset($orcamento[$medida->id]);
        }

        session()->put('orcamento', $orcamento);

        return redirect()->route('orcamento');
    }

    public function destroy()
    {
        $medida = ProdutoMedida::find(request('medida'));

        if (! $medida) return back();

        $orcamento = session()->get('orcamento', []);

        if (array_key_exists($medida->id, $orcamento)) {
            unset($orcamento[$medida->id]);
        }

        session()->put('orcamento', $orcamento);

        return redirect()->route('orcamento');
    }

    public function frete()
    {
        $this->validate(request(), ['cep' => 'regex:/[0-9]+/']);

        return $this->calculaFrete($this->medidasOrcamento(), request('cep'));
    }

    public function post(OrcamentosRequest $request, Orcamento $orcamento)
    {
        $data = $request->all();

        $medidas = $this->medidasOrcamento();
        if (! count($medidas)) return back();

        $valorTotal = dinheiro($this->valorTotal($medidas));

        $frete = $this->calculaFrete($medidas, request('cep'));
        if (array_key_exists('erro', $frete)) {
            $valorFrete = 'CEP não é coberto pelo sistema de frete';
            $total = $valorTotal;
        } else {
            $valorFrete = $frete['frete'];
            $total = $frete['total'];
        }

        $orcamentoHtml = '';
        foreach($medidas as $medida) {
            $unitario = dinheiro($medida->valorParaCalculo());
            $subtotal = dinheiro($medida->valorParaCalculo() * $medida->quantidade);

            $orcamentoHtml .= "
                <p>
                    ".($medida->produto->codigo ? "(código: {$medida->produto->codigo})<br>" : "")."
                    {$medida->produto->titulo} - {$medida->titulo}<br>
                    Quantidade: {$medida->quantidade} unidade(s)<br>
                    Preço Unitário: {$unitario}<br>
                    Subtotal: {$subtotal}
                </p>";
        }

        $orcamentoHtml .= "
            <hr>
            <p>
                Total Orçado: {$valorTotal}<br>
                Frete: {$valorFrete}<br>
                <strong>Total: {$total}</strong>
            </p>
        ";

        $data['orcamento'] = trim(preg_replace('/\s+/', ' ', $orcamentoHtml));

        $loja = $this->lojaOrcamento($medidas);
        $data['loja'] = $loja->key;
        $data['tie']  = $loja->tie;

        $model = $orcamento->create($data);

        $data['id'] = $model->id;

        $this->sendMail($data);

        session()->forget('orcamento');

        return back()->with('success', true);
    }

    private function sendMail($data)
    {
        $emailKey = $data['loja'] === 'gravi' ? 'g_email' : 'email';

        if (! $email = Contato::first()->{$emailKey}) {
           return false;
        }

        Mail::send('emails.orcamento', $data, function($m) use ($email, $data)
        {
            $m->to($email, config('app.name'))
               ->subject('[ORÇAMENTO] '.config('app.name'))
               ->replyTo($data['email'], $data['nome']);
        });
    }

    protected function lojaOrcamento(Collection $medidas)
    {
        $lojasArr = Tools::lojas();

        $loja = new \stdClass();
        $qtd  = array_combine(
            array_keys($lojasArr),
            array_pad([], count($lojasArr), 0)
        );

        foreach($medidas as $medida) {
            foreach($lojasArr as $slug => $label) {
                if (str_contains($slug, explode(',', $medida->produto->lojas))) {
                    $qtd[$slug] = $qtd[$slug] + 1;
                }
            }
        };

        $isTie = count(array_unique($qtd)) === 1;

        if ($isTie) {
            $lastTie = Orcamento::orderBy('id', 'desc')->where('tie', true)->first();
            if ($lastTie) {
                unset($qtd[$lastTie->loja]);
            }

            $key = array_rand($qtd);
        } else {
            $key = array_keys($qtd, max($qtd))[0];
        }

        $loja->key = $key;
        $loja->tie = $isTie;

        return $loja;
    }

    protected function medidasOrcamento()
    {
        $orcamento = session('orcamento', []);

        if (! count($orcamento)) return collect([]);

        $medidas = ProdutoMedida::with('produto')
            ->whereHas('produto', function ($query) {
                $query->where('ativo', '=', 1);
            })
            ->whereIn('id', array_keys($orcamento))
            ->orderBy(\DB::raw('FIELD(`id`, ' . implode(
                ',',
                array_keys($orcamento)
            ) . ')'))
            ->get();

        return $medidas->each(function($medida) use ($orcamento) {
            $medida->quantidade = $orcamento[$medida->id];
        });
    }

    protected function valorTotal(Collection $medidas)
    {
        return $medidas->reduce(function($carry, $item) {
            $carry += ($item->valorParaCalculo() * $item->quantidade);
            return $carry;
        }, 0);
    }

    protected function calculaFrete(Collection $medidas, $cep)
    {
        $cep = substr($cep, 0, 5);

        $baseCalculo = Frete::where('cep_de', '<=', $cep)
            ->where('cep_ate', '>=', $cep)
            ->first();

        if (! $baseCalculo) {
            return [
                'erro' => 'O CEP informado não é coberto pelo nosso sistema de frete. Favor solicitar cotação pelo formulário.'
            ];
        }

        $freteTotal = $medidas->map(function($medida) use ($baseCalculo) {
            switch (true) {
                case $medida->cubagem <= 20:
                    $valor_cubagem = $baseCalculo->de0_a_20;
                    break;
                case $medida->cubagem > 20 && $medida->cubagem <= 50:
                    $valor_cubagem = $baseCalculo->de20_a_50;
                    break;
                case $medida->cubagem > 50 && $medida->cubagem <= 100:
                    $valor_cubagem = $baseCalculo->de50_a_100;
                    break;
                case $medida->cubagem > 100 && $medida->cubagem <= 150:
                    $valor_cubagem = $baseCalculo->de100_a_150;
                    break;
                case $medida->cubagem > 150 && $medida->cubagem <= 200:
                    $valor_cubagem = $baseCalculo->de150_a_200;
                    break;
                case $medida->cubagem > 200:
                    $valor_cubagem = $baseCalculo->mais_de_200;
                    break;
            }

            $valor   = $medida->valorParaCalculo() / 100;
            $ad      = ($valor / 100) * $baseCalculo->ad;
            $pedagio = ($medida->peso / 100) * $baseCalculo->pedagio;
            $taxas   = $baseCalculo->taxas_diversas;
            $gris    = ($valor / 100) * $baseCalculo->gris;
            $coleta  = $baseCalculo->coleta;
            $divisao = $baseCalculo->divisao == 0 ? 1 : $baseCalculo->divisao;

            $total_frete   = $valor_cubagem + $ad + $gris + $pedagio + $taxas;
            $total_divisao = $total_frete / $divisao;
            $total_frete   = $total_divisao + $coleta;
            $total_frete   = $total_frete / $divisao;

            if ($ad == 0 && $pedagio == 0 && $gris == 0) {
                $total_frete = $coleta;
            }

            return $total_frete * $medida->quantidade;
        })->reduce(function($carry, $item) {
            return $carry += $item;
        }, 0);

        if ($freteTotal == 0 || $baseCalculo->valor_isento > 0 && $baseCalculo->valor_isento > $freteTotal) {
            $freteTotal = 0;
            $valorFrete = 'Grátis';
        } else {
            $freteTotal = $freteTotal * 100;
            $valorFrete = dinheiro($freteTotal);
        }

        $valorProdutos = $this->valorTotal($medidas);

        if ($valorProdutos > 0) {
            $valorTotal = dinheiro($valorProdutos + $freteTotal);
        } else {
            $valorTotal = dinheiro(0);
        }

        return [
            'frete' => $valorFrete,
            'total' => $valorTotal
        ];
    }
}

laravel/app/Http/Controllers/Painel/ProdutosDestaquesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\ProdutoDestaque;

class ProdutosDestaquesController extends Controller
{
    public function index()
    {
        $registros = ProdutoDestaque::with('produto')->ordenados()->get();

        return view('painel.produtos.destaques.index', compact('registros'));
    }

    public function destroy(ProdutoDestaque $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.produtos.destaques.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/orcamentos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>Orçamentos</h2>
    </legend>

    <div class="well">
        <div class="btn-group">
            <a href="{{ route('painel.orcamentos.index') }}" class="btn btn-info @if(!request('loja')) active @endif">Todas as lojas</a>
            @foreach(Tools::lojas() as $key => $label)
            <a href="{{ route('painel.orcamentos.index', ['loja' => $key]) }}" class="btn btn-info @if(request('loja') == $key) active @endif">{{ $label }}</a>
            @endforeach
        </div>
    </div>

    @if(!count($orcamentos))
    <div class="alert alert-warning" role="alert">Nenhum orçamento recebido.</div>
    @else
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Data</th>
                <th>Loja</th>
                <th>Nome</th>
                <th>E-mail</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($orcamentos as $orcamento)
            <tr class="tr-row @if(!$orcamento->lido) warning @endif">
                <td data-order="{{ $orcamento->created_at_order }}">{{ $orcamento->created_at }}</td>
                <td>{{ Tools::lojas()[$orcamento->loja] }}</td>
                <td>{{ $orcamento->nome }}</td>
                <td>
                    <button class="btn btn-info btn-sm clipboard" data-clipboard-text="{{ $orcamento->email }}" style="margin-right:5px;border:0;transition:background .3s">
                        <span class="glyphicon glyphicon-copy"></span>
                    </button>
                    {{ $orcamento->email }}
                </td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.orcamentos.destroy', $orcamento->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.orcamentos.show', $orcamento->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-align-left" style="margin-right:10px;"></span>Ver pedido
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>

                        <a href="{{ route('painel.orcamentos.toggle', $orcamento->id) }}" class="btn btn-sm pull-left {{ ($orcamento->lido ? 'btn-warning' : 'btn-success') }}">
                            <span class="glyphicon small {{ ($orcamento->lido ? 'glyphicon-repeat' : 'glyphicon-ok') }}"></span>
                        </a>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>

        @endforeach
        </tbody>
    </table>

    {!! $orcamentos->appends($_GET)->render() !!}
    @endif

@stop

laravel/resources/views/painel/orcamentos/show.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2>Orçamento #{{ $orcamento->id }}</h2>
    </legend>

    <div class="form-group">
        <label>Data</label>
        <div class="well">{{ $orcamento->created_at }}</div>
    </div>

    <div class="form-group">
        <label>Nome</label>
        <div class="well">{{ $orcamento->nome }}</div>
    </div>

    <div class="form-group">
        <label>E-mail</label>
        <div class="well">
            <button class="btn btn-info btn-sm clipboard" data-clipboard-text="{{ $orcamento->email }}" style="margin-right:5px;border:0;transition:background .3s">
                <span class="glyphicon glyphicon-copy"></span>
            </button>
            {{ $orcamento->email }}
        </div>
    </div>

@if($orcamento->telefone)
    <div class="form-group">
        <label>Telefone</label>
        <div class="well">{{ $orcamento->telefone }}</div>
    </div>
@endif

@if($orcamento->mensagem)
    <div class="form-group">
        <label>Mensagem</label>
        <div class="well">{{ $orcamento->mensagem }}</div>
    </div>
@endif

    <div class="form-group">
        <label>Pedido</label>
        <div class="well well-pedido">{!! $orcamento->orcamento !!}</div>
    </div>

    <style>
        .well-pedido hr { border-color: #ccc; }
        .well-pedido p:last-child { margin-bottom: 0; }
    </style>

    <a href="{{ route('painel.orcamentos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

@stop